/*******************************************************************************
 *                                                                             *
 * This file is generated by BitFontCreator Pro v3.7                           *
 * by Iseatech Software   http://www.iseasoft.com/bfc.htm                      *
 *                        support@iseatech.com                                 *
 *                                                                             *
 * Font name: Lucida Sans Unicode                                              *
 * Font width: 0 (proportional font)                                           *
 * Font height: 16                                                             *
 * Encode: Unicode                                                             *
 * Data length: 8 bits                                                         *
 * Invert bits: No                                                             *
 * Data format: Little Endian, Column based, Column preferred, Unpacked        *
 *                                                                             *
 * Create time: 11:29 04-06-2016                                               *
 *******************************************************************************/

#include "bfcfont.h"

/* The following line needs to be included in any file selecting the
   font.
*/
extern const BFC_FONT fontLucida_Sans_Unicode16h_colcolLit;

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0020[   8] = { /* code 0020 */
  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0021[   8] = { /* code 0021 */
  0x00,  0x00,  0xF0,  0x17,  0x00,  0x00,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0022[  10] = { /* code 0022 */
  0x00,  0x00,  0x38,  0x00,  0x00,  0x00,  0x38,  0x00,
  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0023[  16] = { /* code 0023 */
  0x00,  0x02,  0x40,  0x1E,  0xE0,  0x03,  0x50,  0x02,
  0x40,  0x1E,  0xE0,  0x03,  0x50,  0x02,  0x40,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0024[  16] = { /* code 0024 */
  0x00,  0x00,  0x60,  0x08,  0x90,  0x10,  0xF8,  0x3F,
  0x10,  0x11,  0x10,  0x0E,  0x00,  0x00,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0025[  18] = { /* code 0025 */
  0xE0,  0x10,  0x10,  0x09,  0x10,  0x05,  0xE0,  0x02,
  0x80,  0x01,  0x40,  0x0E,  0x20,  0x11,  0x10,  0x11,
  0x08,  0x0E
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0026[  18] = { /* code 0026 */
  0x00,  0x00,  0x00,  0x0E,  0x60,  0x19,  0x90,  0x11,
  0x90,  0x12,  0x60,  0x0C,  0x00,  0x18,  0x00,  0x17,
  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0027[   6] = { /* code 0027 */
  0x00,  0x00,  0x38,  0x00,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0028[   8] = { /* code 0028 */
  0x00,  0x00,  0xC0,  0x0F,  0x30,  0x30,  0x08,  0x40
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0029[   8] = { /* code 0029 */
  0x08,  0x40,  0x30,  0x30,  0xC0,  0x0F,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_002A[  12] = { /* code 002A */
  0x20,  0x00,  0xC0,  0x01,  0x30,  0x00,  0xC0,  0x01,
  0x20,  0x00,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_002B[  20] = { /* code 002B */
  0x00,  0x00,  0x00,  0x02,  0x00,  0x02,  0x00,  0x02,
  0xC0,  0x1F,  0x00,  0x02,  0x00,  0x02,  0x00,  0x02,
  0x00,  0x00,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_002C[   8] = { /* code 002C */
  0x00,  0x00,  0x00,  0x58,  0x00,  0x38,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_002D[  16] = { /* code 002D */
  0x00,  0x00,  0x00,  0x02,  0x00,  0x02,  0x00,  0x02,
  0x00,  0x02,  0x00,  0x02,  0x00,  0x02,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_002E[   8] = { /* code 002E */
  0x00,  0x00,  0x00,  0x18,  0x00,  0x18,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_002F[  14] = { /* code 002F */
  0x00,  0x00,  0x00,  0x70,  0x00,  0x0E,  0xC0,  0x01,
  0x30,  0x00,  0x00,  0x00,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0030[  16] = { /* code 0030 */
  0xC0,  0x07,  0x20,  0x08,  0x10,  0x10,  0x10,  0x10,
  0x10,  0x10,  0x20,  0x08,  0xC0,  0x07,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0031[  16] = { /* code 0031 */
  0x00,  0x00,  0x10,  0x00,  0x10,  0x00,  0xF0,  0x1F,
  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0032[  16] = { /* code 0032 */
  0x00,  0x00,  0x20,  0x18,  0x10,  0x14,  0x10,  0x12,
  0x10,  0x12,  0x10,  0x11,  0xE0,  0x10,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0033[  16] = { /* code 0033 */
  0x00,  0x00,  0x20,  0x08,  0x10,  0x11,  0x10,  0x11,
  0x90,  0x11,  0x60,  0x0E,  0x00,  0x00,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0034[  16] = { /* code 0034 */
  0x00,  0x00,  0x00,  0x03,  0x80,  0x02,  0x40,  0x02,
  0x20,  0x02,  0xF0,  0x1F,  0x00,  0x02,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0035[  16] = { /* code 0035 */
  0x00,  0x00,  0xF0,  0x10,  0x90,  0x10,  0x90,  0x10,
  0x10,  0x11,  0x10,  0x0E,  0x00,  0x00,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0036[  16] = { /* code 0036 */
  0x00,  0x00,  0xC0,  0x07,  0x20,  0x09,  0x90,  0x10,
  0x90,  0x10,  0x10,  0x09,  0x10,  0x06,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0037[  16] = { /* code 0037 */
  0x00,  0x00,  0x10,  0x00,  0x10,  0x18,  0x10,  0x06,
  0x90,  0x01,  0x50,  0x00,  0x30,  0x00,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0038[  16] = { /* code 0038 */
  0x00,  0x00,  0x60,  0x0E,  0x90,  0x11,  0x10,  0x11,
  0x10,  0x11,  0x90,  0x11,  0x60,  0x0E,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0039[  16] = { /* code 0039 */
  0x00,  0x00,  0xC0,  0x10,  0x20,  0x11,  0x10,  0x12,
  0x10,  0x12,  0x20,  0x09,  0xC0,  0x07,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_003A[   8] = { /* code 003A */
  0x00,  0x00,  0x40,  0x10,  0x00,  0x00,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_003B[   8] = { /* code 003B */
  0x00,  0x40,  0x40,  0x30,  0x00,  0x00,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_003C[  20] = { /* code 003C */
  0x00,  0x00,  0x00,  0x02,  0x00,  0x02,  0x00,  0x05,
  0x00,  0x05,  0x80,  0x08,  0x80,  0x08,  0x80,  0x08,
  0x40,  0x10,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_003D[  20] = { /* code 003D */
  0x00,  0x00,  0x80,  0x04,  0x80,  0x04,  0x80,  0x04,
  0x80,  0x04,  0x80,  0x04,  0x80,  0x04,  0x80,  0x04,
  0x80,  0x04,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_003E[  20] = { /* code 003E */
  0x00,  0x00,  0x40,  0x10,  0x80,  0x08,  0x80,  0x08,
  0x80,  0x08,  0x00,  0x05,  0x00,  0x05,  0x00,  0x02,
  0x00,  0x02,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_003F[  10] = { /* code 003F */
  0x10,  0x00,  0x10,  0x16,  0x10,  0x01,  0x90,  0x00,
  0x60,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0040[  22] = { /* code 0040 */
  0x80,  0x07,  0x40,  0x08,  0x20,  0x17,  0xA0,  0x14,
  0x50,  0x12,  0x50,  0x17,  0xD0,  0x04,  0x50,  0x04,
  0x20,  0x02,  0xC0,  0x01,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0041[  18] = { /* code 0041 */
  0x00,  0x10,  0x00,  0x0E,  0x80,  0x05,  0x60,  0x04,
  0x10,  0x04,  0x60,  0x04,  0x80,  0x05,  0x00,  0x0E,
  0x00,  0x10
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0042[  14] = { /* code 0042 */
  0x00,  0x00,  0xF0,  0x1F,  0x10,  0x11,  0x10,  0x11,
  0x90,  0x12,  0x60,  0x0C,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0043[  18] = { /* code 0043 */
  0xC0,  0x07,  0x20,  0x08,  0x10,  0x10,  0x10,  0x10,
  0x10,  0x10,  0x10,  0x10,  0x10,  0x10,  0x20,  0x08,
  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0044[  20] = { /* code 0044 */
  0x00,  0x00,  0xF0,  0x1F,  0x10,  0x10,  0x10,  0x10,
  0x10,  0x10,  0x10,  0x10,  0x10,  0x10,  0x20,  0x08,
  0xC0,  0x07,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0045[  14] = { /* code 0045 */
  0x00,  0x00,  0xF0,  0x1F,  0x10,  0x11,  0x10,  0x11,
  0x10,  0x11,  0x10,  0x11,  0x10,  0x10
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0046[  14] = { /* code 0046 */
  0x00,  0x00,  0xF0,  0x1F,  0x10,  0x01,  0x10,  0x01,
  0x10,  0x01,  0x10,  0x00,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0047[  18] = { /* code 0047 */
  0x00,  0x00,  0xC0,  0x07,  0x20,  0x08,  0x10,  0x10,
  0x10,  0x10,  0x10,  0x10,  0x10,  0x10,  0x10,  0x1E,
  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0048[  20] = { /* code 0048 */
  0x00,  0x00,  0xF0,  0x1F,  0x00,  0x01,  0x00,  0x01,
  0x00,  0x01,  0x00,  0x01,  0x00,  0x01,  0xF0,  0x1F,
  0x00,  0x00,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0049[   8] = { /* code 0049 */
  0x00,  0x00,  0xF0,  0x1F,  0x00,  0x00,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_004A[   8] = { /* code 004A */
  0x00,  0x40,  0x00,  0x40,  0x00,  0x40,  0xF0,  0x3F
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_004B[  16] = { /* code 004B */
  0x00,  0x00,  0xF0,  0x1F,  0x00,  0x01,  0x80,  0x02,
  0x40,  0x04,  0x20,  0x08,  0x10,  0x10,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_004C[  14] = { /* code 004C */
  0x00,  0x00,  0xF0,  0x1F,  0x00,  0x10,  0x00,  0x10,
  0x00,  0x10,  0x00,  0x10,  0x00,  0x10
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_004D[  22] = { /* code 004D */
  0x00,  0x00,  0xF0,  0x1F,  0x30,  0x00,  0xC0,  0x01,
  0x00,  0x06,  0x00,  0x08,  0x00,  0x06,  0xC0,  0x01,
  0x30,  0x00,  0xF0,  0x1F,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_004E[  20] = { /* code 004E */
  0x00,  0x00,  0xF0,  0x1F,  0x30,  0x00,  0xC0,  0x00,
  0x00,  0x01,  0x00,  0x06,  0x00,  0x18,  0xF0,  0x1F,
  0x00,  0x00,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_004F[  20] = { /* code 004F */
  0xC0,  0x07,  0x20,  0x08,  0x10,  0x10,  0x10,  0x10,
  0x10,  0x10,  0x10,  0x10,  0x10,  0x10,  0x20,  0x08,
  0xC0,  0x07,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0050[  14] = { /* code 0050 */
  0x00,  0x00,  0xF0,  0x1F,  0x10,  0x01,  0x10,  0x01,
  0x10,  0x01,  0x10,  0x01,  0xE0,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0051[  20] = { /* code 0051 */
  0xC0,  0x07,  0x20,  0x08,  0x10,  0x10,  0x10,  0x10,
  0x10,  0x10,  0x10,  0x10,  0x10,  0x30,  0x20,  0x28,
  0xC0,  0x47,  0x00,  0x40
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0052[  16] = { /* code 0052 */
  0x00,  0x00,  0xF0,  0x1F,  0x10,  0x01,  0x10,  0x01,
  0x10,  0x03,  0x90,  0x04,  0x60,  0x08,  0x00,  0x10
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0053[  14] = { /* code 0053 */
  0x60,  0x10,  0x90,  0x10,  0x10,  0x11,  0x10,  0x11,
  0x10,  0x12,  0x00,  0x0C,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0054[  16] = { /* code 0054 */
  0x10,  0x00,  0x10,  0x00,  0x10,  0x00,  0xF0,  0x1F,
  0x10,  0x00,  0x10,  0x00,  0x10,  0x00,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0055[  18] = { /* code 0055 */
  0x00,  0x00,  0xF0,  0x0F,  0x00,  0x10,  0x00,  0x10,
  0x00,  0x10,  0x00,  0x10,  0x00,  0x10,  0xF0,  0x0F,
  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0056[  18] = { /* code 0056 */
  0x10,  0x00,  0xE0,  0x00,  0x00,  0x07,  0x00,  0x18,
  0x00,  0x18,  0x00,  0x07,  0xE0,  0x00,  0x10,  0x00,
  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0057[  22] = { /* code 0057 */
  0x30,  0x00,  0xC0,  0x07,  0x00,  0x18,  0x00,  0x0E,
  0xC0,  0x01,  0x30,  0x00,  0xC0,  0x01,  0x00,  0x0E,
  0x00,  0x18,  0xC0,  0x07,  0x30,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0058[  16] = { /* code 0058 */
  0x10,  0x10,  0x20,  0x08,  0xC0,  0x06,  0x00,  0x01,
  0x00,  0x01,  0xC0,  0x06,  0x20,  0x08,  0x10,  0x10
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0059[  16] = { /* code 0059 */
  0x10,  0x00,  0x60,  0x00,  0x80,  0x00,  0x00,  0x1F,
  0x80,  0x00,  0x60,  0x00,  0x10,  0x00,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_005A[  16] = { /* code 005A */
  0x10,  0x18,  0x10,  0x14,  0x10,  0x12,  0x10,  0x11,
  0x90,  0x10,  0x50,  0x10,  0x30,  0x10,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_005B[   8] = { /* code 005B */
  0x00,  0x00,  0xF8,  0x7F,  0x08,  0x40,  0x08,  0x40
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_005C[  14] = { /* code 005C */
  0x00,  0x00,  0x70,  0x00,  0x80,  0x03,  0x00,  0x1C,
  0x00,  0x60,  0x00,  0x00,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_005D[   8] = { /* code 005D */
  0x08,  0x40,  0x08,  0x40,  0xF8,  0x7F,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_005E[  16] = { /* code 005E */
  0x00,  0x04,  0x00,  0x03,  0xC0,  0x00,  0x30,  0x00,
  0xC0,  0x00,  0x00,  0x03,  0x00,  0x04,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_005F[  14] = { /* code 005F */
  0x00,  0x00,  0x00,  0x20,  0x00,  0x20,  0x00,  0x20,
  0x00,  0x20,  0x00,  0x20,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0060[  16] = { /* code 0060 */
  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x08,  0x00,
  0x18,  0x00,  0x10,  0x00,  0x00,  0x00,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0061[  14] = { /* code 0061 */
  0x00,  0x00,  0x00,  0x0C,  0x80,  0x12,  0x40,  0x12,
  0x40,  0x12,  0x80,  0x1F,  0x00,  0x10
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0062[  16] = { /* code 0062 */
  0x00,  0x00,  0xF8,  0x1F,  0x80,  0x10,  0x40,  0x10,
  0x40,  0x10,  0x40,  0x10,  0x80,  0x0F,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0063[  14] = { /* code 0063 */
  0x00,  0x00,  0x80,  0x0F,  0x40,  0x10,  0x40,  0x10,
  0x40,  0x10,  0x40,  0x10,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0064[  16] = { /* code 0064 */
  0x00,  0x00,  0x80,  0x0F,  0x40,  0x10,  0x40,  0x10,
  0x40,  0x10,  0x40,  0x08,  0xF8,  0x1F,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0065[  14] = { /* code 0065 */
  0x00,  0x00,  0x80,  0x0F,  0x40,  0x12,  0x40,  0x12,
  0x40,  0x12,  0x80,  0x13,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0066[  10] = { /* code 0066 */
  0x40,  0x00,  0xF0,  0x1F,  0x48,  0x00,  0x48,  0x00,
  0x08,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0067[  16] = { /* code 0067 */
  0x00,  0x00,  0x80,  0x0F,  0x40,  0x90,  0x40,  0x90,
  0x40,  0x90,  0x40,  0x48,  0xC0,  0x3F,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0068[  16] = { /* code 0068 */
  0x00,  0x00,  0xF8,  0x1F,  0x80,  0x00,  0x40,  0x00,
  0x40,  0x00,  0x40,  0x00,  0x80,  0x1F,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0069[   8] = { /* code 0069 */
  0x00,  0x00,  0xD0,  0x1F,  0x00,  0x00,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_006A[   8] = { /* code 006A */
  0x00,  0x80,  0x00,  0x80,  0x00,  0x80,  0xD0,  0x7F
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_006B[  16] = { /* code 006B */
  0x00,  0x00,  0xF8,  0x1F,  0x00,  0x02,  0x00,  0x05,
  0x80,  0x08,  0x40,  0x10,  0x00,  0x00,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_006C[   8] = { /* code 006C */
  0x00,  0x00,  0xF8,  0x1F,  0x00,  0x00,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_006D[  24] = { /* code 006D */
  0x00,  0x00,  0xC0,  0x1F,  0x80,  0x00,  0x40,  0x00,
  0x40,  0x00,  0x80,  0x1F,  0x80,  0x00,  0x40,  0x00,
  0x40,  0x00,  0x80,  0x1F,  0x00,  0x00,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_006E[  16] = { /* code 006E */
  0x00,  0x00,  0xC0,  0x1F,  0x80,  0x00,  0x40,  0x00,
  0x40,  0x00,  0x40,  0x00,  0x80,  0x1F,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_006F[  16] = { /* code 006F */
  0x00,  0x00,  0x80,  0x0F,  0x40,  0x10,  0x40,  0x10,
  0x40,  0x10,  0x40,  0x10,  0x80,  0x0F,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0070[  16] = { /* code 0070 */
  0x00,  0x00,  0xC0,  0xFF,  0x80,  0x10,  0x40,  0x10,
  0x40,  0x10,  0x40,  0x10,  0x80,  0x0F,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0071[  16] = { /* code 0071 */
  0x00,  0x00,  0x80,  0x0F,  0x40,  0x10,  0x40,  0x10,
  0x40,  0x10,  0x40,  0x08,  0xC0,  0xFF,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0072[  10] = { /* code 0072 */
  0x00,  0x00,  0xC0,  0x1F,  0x80,  0x00,  0x40,  0x00,
  0x40,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0073[  14] = { /* code 0073 */
  0x00,  0x00,  0x80,  0x11,  0x40,  0x12,  0x40,  0x12,
  0x40,  0x12,  0x00,  0x0C,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0074[  10] = { /* code 0074 */
  0x40,  0x00,  0xE0,  0x0F,  0x40,  0x10,  0x40,  0x10,
  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0075[  16] = { /* code 0075 */
  0x00,  0x00,  0xC0,  0x0F,  0x00,  0x10,  0x00,  0x10,
  0x00,  0x10,  0x00,  0x08,  0xC0,  0x1F,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0076[  14] = { /* code 0076 */
  0x40,  0x00,  0x80,  0x03,  0x00,  0x0C,  0x00,  0x10,
  0x00,  0x0C,  0x80,  0x03,  0x40,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0077[  20] = { /* code 0077 */
  0xC0,  0x00,  0x00,  0x07,  0x00,  0x18,  0x00,  0x07,
  0xC0,  0x00,  0x00,  0x07,  0x00,  0x18,  0x00,  0x07,
  0xC0,  0x00,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0078[  16] = { /* code 0078 */
  0x00,  0x00,  0x40,  0x10,  0x80,  0x08,  0x00,  0x07,
  0x00,  0x07,  0x80,  0x08,  0x40,  0x10,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_0079[  14] = { /* code 0079 */
  0x40,  0x00,  0x80,  0x03,  0x00,  0x8C,  0x00,  0x70,
  0x00,  0x0C,  0x80,  0x03,  0x40,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_007A[  14] = { /* code 007A */
  0x00,  0x00,  0x40,  0x18,  0x40,  0x14,  0x40,  0x12,
  0x40,  0x11,  0xC0,  0x10,  0x40,  0x10
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_007B[   8] = { /* code 007B */
  0x00,  0x01,  0xF0,  0x3E,  0x08,  0x40,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_007C[  10] = { /* code 007C */
  0x00,  0x00,  0x00,  0x00,  0xF8,  0x7F,  0x00,  0x00,
  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_007D[   8] = { /* code 007D */
  0x00,  0x00,  0x08,  0x40,  0xF0,  0x3E,  0x00,  0x01
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_007E[  16] = { /* code 007E */
  0x00,  0x00,  0x00,  0x03,  0x00,  0x01,  0x00,  0x01,
  0x00,  0x02,  0x00,  0x02,  0x00,  0x03,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_3053[  26] = { /* code 3053 */
  0x00,  0x0E,  0x08,  0x11,  0x08,  0x10,  0x08,  0x10,
  0x08,  0x10,  0x08,  0x10,  0x08,  0x10,  0x08,  0x10,
  0x00,  0x08,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,
  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_3061[  28] = { /* code 3061 */
  0x10,  0x00,  0x10,  0x06,  0xF0,  0x01,  0x1E,  0x01,
  0x90,  0x20,  0x90,  0x20,  0x90,  0x20,  0x10,  0x11,
  0x00,  0x0E,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,
  0x00,  0x00,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_306B[  28] = { /* code 306B */
  0x00,  0x00,  0xF0,  0x0F,  0x0C,  0x30,  0x00,  0x00,
  0x00,  0x0E,  0x08,  0x11,  0x08,  0x10,  0x08,  0x10,
  0x08,  0x10,  0x08,  0x10,  0x00,  0x00,  0x00,  0x00,
  0x00,  0x00,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_306F[  30] = { /* code 306F */
  0x00,  0x00,  0xF0,  0x0F,  0x0C,  0x30,  0x00,  0x00,
  0x20,  0x1C,  0x20,  0x22,  0x20,  0x22,  0x20,  0x22,
  0xFC,  0x1F,  0x20,  0x04,  0x20,  0x08,  0x00,  0x00,
  0x00,  0x00,  0x00,  0x00,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_3093[  30] = { /* code 3093 */
  0x00,  0x3C,  0x80,  0x03,  0x70,  0x01,  0x8C,  0x00,
  0x80,  0x00,  0x00,  0x1F,  0x00,  0x20,  0x00,  0x20,
  0x00,  0x10,  0x00,  0x0F,  0x00,  0x00,  0x00,  0x00,
  0x00,  0x00,  0x00,  0x00,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_30AB[  26] = { /* code 30AB */
  0x10,  0x20,  0x10,  0x18,  0x10,  0x06,  0xFE,  0x01,
  0x10,  0x00,  0x10,  0x20,  0x10,  0x20,  0x10,  0x20,
  0xF0,  0x1F,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,
  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_30C3[  22] = { /* code 30C3 */
  0x40,  0x00,  0x80,  0x21,  0x20,  0x20,  0xC0,  0x10,
  0x00,  0x08,  0x00,  0x06,  0xE0,  0x01,  0x00,  0x00,
  0x00,  0x00,  0x00,  0x00,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_30C9[  26] = { /* code 30C9 */
  0x00,  0x00,  0xFE,  0x3F,  0x20,  0x00,  0x20,  0x00,
  0x40,  0x00,  0x5C,  0x00,  0x80,  0x00,  0x1C,  0x01,
  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,
  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_30D7[  28] = { /* code 30D7 */
  0x10,  0x00,  0x10,  0x20,  0x10,  0x20,  0x10,  0x20,
  0x10,  0x10,  0x10,  0x10,  0x1C,  0x08,  0x12,  0x06,
  0xF2,  0x01,  0x0C,  0x00,  0x00,  0x00,  0x00,  0x00,
  0x00,  0x00,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_30EB[  30] = { /* code 30EB */
  0x00,  0x20,  0x00,  0x20,  0x00,  0x18,  0xF8,  0x07,
  0x00,  0x00,  0x00,  0x00,  0xFC,  0x3F,  0x00,  0x20,
  0x00,  0x10,  0x00,  0x0C,  0x80,  0x03,  0x00,  0x00,
  0x00,  0x00,  0x00,  0x00,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_30EF[  28] = { /* code 30EF */
  0xF8,  0x01,  0x08,  0x00,  0x08,  0x00,  0x08,  0x20,
  0x08,  0x20,  0x08,  0x10,  0x08,  0x10,  0x08,  0x0C,
  0xF8,  0x03,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,
  0x00,  0x00,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_30FC[  30] = { /* code 30FC */
  0x00,  0x00,  0x00,  0x00,  0x40,  0x00,  0x80,  0x00,
  0x80,  0x00,  0x80,  0x00,  0x80,  0x00,  0x80,  0x00,
  0x80,  0x00,  0x80,  0x00,  0x80,  0x00,  0x00,  0x00,
  0x00,  0x00,  0x00,  0x00,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_4E16[  36] = { /* code 4E16 */
  0x00,  0x00,  0x20,  0x00,  0x20,  0x00,  0xFE,  0x3F,
  0x20,  0x20,  0x20,  0x20,  0x20,  0x20,  0xFE,  0x23,
  0x20,  0x22,  0x20,  0x22,  0xFE,  0x23,  0x20,  0x20,
  0x20,  0x20,  0x20,  0x00,  0x00,  0x00,  0x00,  0x00,
  0x00,  0x00,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_4F60[  36] = { /* code 4F60 */
  0x00,  0x00,  0x80,  0x01,  0x60,  0x00,  0xFC,  0x3F,
  0x02,  0x00,  0x20,  0x08,  0x18,  0x07,  0x8E,  0x20,
  0x08,  0x20,  0xF8,  0x3F,  0x08,  0x00,  0x88,  0x00,
  0x28,  0x03,  0x18,  0x0C,  0x00,  0x00,  0x00,  0x00,
  0x00,  0x00,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_597D[  36] = { /* code 597D */
  0x00,  0x00,  0x88,  0x23,  0x78,  0x12,  0x0E,  0x0C,
  0x08,  0x0B,  0xF8,  0x10,  0x00,  0x00,  0x84,  0x00,
  0x84,  0x20,  0x84,  0x20,  0xE4,  0x3F,  0x94,  0x00,
  0x8C,  0x00,  0x80,  0x00,  0x00,  0x00,  0x00,  0x00,
  0x00,  0x00,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_676F[  36] = { /* code 676F */
  0x00,  0x00,  0x08,  0x03,  0xC8,  0x00,  0xFE,  0x3F,
  0x48,  0x00,  0x08,  0x02,  0x04,  0x01,  0x84,  0x00,
  0x44,  0x00,  0xE4,  0x3F,  0x1C,  0x00,  0x84,  0x00,
  0x04,  0x01,  0x04,  0x02,  0x00,  0x00,  0x00,  0x00,
  0x00,  0x00,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_754C[  36] = { /* code 754C */
  0x00,  0x00,  0x00,  0x02,  0x00,  0x02,  0x7E,  0x21,
  0x4A,  0x11,  0xCA,  0x0E,  0x4A,  0x00,  0x7E,  0x00,
  0x4A,  0x00,  0xCA,  0x3E,  0x4A,  0x01,  0x7E,  0x01,
  0x00,  0x02,  0x00,  0x02,  0x00,  0x00,  0x00,  0x00,
  0x00,  0x00,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_B155[  36] = { /* code B155 */
  0x00,  0x00,  0x3E,  0x00,  0x40,  0x18,  0x40,  0x24,
  0x40,  0x24,  0x40,  0x24,  0x40,  0x24,  0x54,  0x24,
  0x54,  0x24,  0x14,  0x24,  0x14,  0x24,  0xFE,  0x19,
  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,
  0x00,  0x00,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_B4DC[  36] = { /* code B4DC */
  0x00,  0x00,  0x00,  0x10,  0x78,  0x10,  0x84,  0x10,
  0x84,  0x10,  0x84,  0x10,  0x84,  0x10,  0x84,  0x10,
  0x84,  0x10,  0x84,  0x10,  0x84,  0x10,  0x84,  0x10,
  0x00,  0x10,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,
  0x00,  0x00,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_C138[  36] = { /* code C138 */
  0x00,  0x00,  0x00,  0x10,  0x00,  0x0C,  0x80,  0x03,
  0x7C,  0x00,  0x80,  0x03,  0x40,  0x1C,  0x40,  0x00,
  0x40,  0x00,  0xFE,  0x3F,  0x00,  0x00,  0xFE,  0x3F,
  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,
  0x00,  0x00,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_C548[  36] = { /* code C548 */
  0x00,  0x00,  0x38,  0x00,  0x44,  0x1C,  0x82,  0x20,
  0x82,  0x20,  0x82,  0x20,  0x44,  0x20,  0x38,  0x20,
  0x00,  0x20,  0x00,  0x20,  0x00,  0x20,  0xFE,  0x27,
  0x20,  0x00,  0x20,  0x00,  0x00,  0x00,  0x00,  0x00,
  0x00,  0x00,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_C694[  36] = { /* code C694 */
  0x00,  0x00,  0x00,  0x10,  0x70,  0x10,  0x88,  0x10,
  0x04,  0x1F,  0x04,  0x11,  0x04,  0x11,  0x04,  0x11,
  0x04,  0x11,  0x04,  0x1F,  0x88,  0x10,  0x70,  0x10,
  0x00,  0x10,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,
  0x00,  0x00,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_C6D4[  36] = { /* code C6D4 */
  0x00,  0x00,  0x40,  0x00,  0x4C,  0x12,  0x52,  0x2A,
  0x52,  0x2A,  0xD2,  0x2B,  0x52,  0x2A,  0x52,  0x2A,
  0x4C,  0x2A,  0xC0,  0x2A,  0x80,  0x2A,  0xFE,  0x25,
  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,
  0x00,  0x00,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_CEF5[  36] = { /* code CEF5 */
  0x00,  0x00,  0x90,  0x00,  0x92,  0x1E,  0x92,  0x28,
  0x52,  0x28,  0x52,  0x28,  0x32,  0x28,  0x1C,  0x28,
  0x10,  0x28,  0x10,  0x28,  0x10,  0x28,  0xFE,  0x1E,
  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,
  0x00,  0x00,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_D558[  36] = { /* code D558 */
  0x00,  0x00,  0x10,  0x00,  0x90,  0x0F,  0x54,  0x10,
  0x54,  0x10,  0x54,  0x10,  0x54,  0x10,  0x90,  0x0F,
  0x10,  0x00,  0x00,  0x00,  0x00,  0x00,  0xFE,  0x3F,
  0x40,  0x00,  0x40,  0x00,  0x00,  0x00,  0x00,  0x00,
  0x00,  0x00,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_FF0C[  24] = { /* code FF0C */
  0x00,  0x00,  0x00,  0x2C,  0x00,  0x1C,  0x00,  0x00,
  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,
  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00
};

const UCHAR abc_fontLucida_Sans_Unicode16h_colcolLit_FF64[  16] = { /* code FF64 */
  0x00,  0x08,  0x00,  0x10,  0x00,  0x20,  0x00,  0x00,
  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00
};

const BFC_CHARINFO fontLucida_Sans_Unicode16h_colcolLit_CharInfo[122] = {
   {   4,   8, {abc_fontLucida_Sans_Unicode16h_colcolLit_0020} }, /* code 0020 */
   {   4,   8, {abc_fontLucida_Sans_Unicode16h_colcolLit_0021} }, /* code 0021 */
   {   5,  10, {abc_fontLucida_Sans_Unicode16h_colcolLit_0022} }, /* code 0022 */
   {   8,  16, {abc_fontLucida_Sans_Unicode16h_colcolLit_0023} }, /* code 0023 */
   {   8,  16, {abc_fontLucida_Sans_Unicode16h_colcolLit_0024} }, /* code 0024 */
   {   9,  18, {abc_fontLucida_Sans_Unicode16h_colcolLit_0025} }, /* code 0025 */
   {   9,  18, {abc_fontLucida_Sans_Unicode16h_colcolLit_0026} }, /* code 0026 */
   {   3,   6, {abc_fontLucida_Sans_Unicode16h_colcolLit_0027} }, /* code 0027 */
   {   4,   8, {abc_fontLucida_Sans_Unicode16h_colcolLit_0028} }, /* code 0028 */
   {   4,   8, {abc_fontLucida_Sans_Unicode16h_colcolLit_0029} }, /* code 0029 */
   {   6,  12, {abc_fontLucida_Sans_Unicode16h_colcolLit_002A} }, /* code 002A */
   {  10,  20, {abc_fontLucida_Sans_Unicode16h_colcolLit_002B} }, /* code 002B */
   {   4,   8, {abc_fontLucida_Sans_Unicode16h_colcolLit_002C} }, /* code 002C */
   {   8,  16, {abc_fontLucida_Sans_Unicode16h_colcolLit_002D} }, /* code 002D */
   {   4,   8, {abc_fontLucida_Sans_Unicode16h_colcolLit_002E} }, /* code 002E */
   {   7,  14, {abc_fontLucida_Sans_Unicode16h_colcolLit_002F} }, /* code 002F */
   {   8,  16, {abc_fontLucida_Sans_Unicode16h_colcolLit_0030} }, /* code 0030 */
   {   8,  16, {abc_fontLucida_Sans_Unicode16h_colcolLit_0031} }, /* code 0031 */
   {   8,  16, {abc_fontLucida_Sans_Unicode16h_colcolLit_0032} }, /* code 0032 */
   {   8,  16, {abc_fontLucida_Sans_Unicode16h_colcolLit_0033} }, /* code 0033 */
   {   8,  16, {abc_fontLucida_Sans_Unicode16h_colcolLit_0034} }, /* code 0034 */
   {   8,  16, {abc_fontLucida_Sans_Unicode16h_colcolLit_0035} }, /* code 0035 */
   {   8,  16, {abc_fontLucida_Sans_Unicode16h_colcolLit_0036} }, /* code 0036 */
   {   8,  16, {abc_fontLucida_Sans_Unicode16h_colcolLit_0037} }, /* code 0037 */
   {   8,  16, {abc_fontLucida_Sans_Unicode16h_colcolLit_0038} }, /* code 0038 */
   {   8,  16, {abc_fontLucida_Sans_Unicode16h_colcolLit_0039} }, /* code 0039 */
   {   4,   8, {abc_fontLucida_Sans_Unicode16h_colcolLit_003A} }, /* code 003A */
   {   4,   8, {abc_fontLucida_Sans_Unicode16h_colcolLit_003B} }, /* code 003B */
   {  10,  20, {abc_fontLucida_Sans_Unicode16h_colcolLit_003C} }, /* code 003C */
   {  10,  20, {abc_fontLucida_Sans_Unicode16h_colcolLit_003D} }, /* code 003D */
   {  10,  20, {abc_fontLucida_Sans_Unicode16h_colcolLit_003E} }, /* code 003E */
   {   5,  10, {abc_fontLucida_Sans_Unicode16h_colcolLit_003F} }, /* code 003F */
   {  11,  22, {abc_fontLucida_Sans_Unicode16h_colcolLit_0040} }, /* code 0040 */
   {   9,  18, {abc_fontLucida_Sans_Unicode16h_colcolLit_0041} }, /* code 0041 */
   {   7,  14, {abc_fontLucida_Sans_Unicode16h_colcolLit_0042} }, /* code 0042 */
   {   9,  18, {abc_fontLucida_Sans_Unicode16h_colcolLit_0043} }, /* code 0043 */
   {  10,  20, {abc_fontLucida_Sans_Unicode16h_colcolLit_0044} }, /* code 0044 */
   {   7,  14, {abc_fontLucida_Sans_Unicode16h_colcolLit_0045} }, /* code 0045 */
   {   7,  14, {abc_fontLucida_Sans_Unicode16h_colcolLit_0046} }, /* code 0046 */
   {   9,  18, {abc_fontLucida_Sans_Unicode16h_colcolLit_0047} }, /* code 0047 */
   {  10,  20, {abc_fontLucida_Sans_Unicode16h_colcolLit_0048} }, /* code 0048 */
   {   4,   8, {abc_fontLucida_Sans_Unicode16h_colcolLit_0049} }, /* code 0049 */
   {   4,   8, {abc_fontLucida_Sans_Unicode16h_colcolLit_004A} }, /* code 004A */
   {   8,  16, {abc_fontLucida_Sans_Unicode16h_colcolLit_004B} }, /* code 004B */
   {   7,  14, {abc_fontLucida_Sans_Unicode16h_colcolLit_004C} }, /* code 004C */
   {  11,  22, {abc_fontLucida_Sans_Unicode16h_colcolLit_004D} }, /* code 004D */
   {  10,  20, {abc_fontLucida_Sans_Unicode16h_colcolLit_004E} }, /* code 004E */
   {  10,  20, {abc_fontLucida_Sans_Unicode16h_colcolLit_004F} }, /* code 004F */
   {   7,  14, {abc_fontLucida_Sans_Unicode16h_colcolLit_0050} }, /* code 0050 */
   {  10,  20, {abc_fontLucida_Sans_Unicode16h_colcolLit_0051} }, /* code 0051 */
   {   8,  16, {abc_fontLucida_Sans_Unicode16h_colcolLit_0052} }, /* code 0052 */
   {   7,  14, {abc_fontLucida_Sans_Unicode16h_colcolLit_0053} }, /* code 0053 */
   {   8,  16, {abc_fontLucida_Sans_Unicode16h_colcolLit_0054} }, /* code 0054 */
   {   9,  18, {abc_fontLucida_Sans_Unicode16h_colcolLit_0055} }, /* code 0055 */
   {   9,  18, {abc_fontLucida_Sans_Unicode16h_colcolLit_0056} }, /* code 0056 */
   {  11,  22, {abc_fontLucida_Sans_Unicode16h_colcolLit_0057} }, /* code 0057 */
   {   8,  16, {abc_fontLucida_Sans_Unicode16h_colcolLit_0058} }, /* code 0058 */
   {   8,  16, {abc_fontLucida_Sans_Unicode16h_colcolLit_0059} }, /* code 0059 */
   {   8,  16, {abc_fontLucida_Sans_Unicode16h_colcolLit_005A} }, /* code 005A */
   {   4,   8, {abc_fontLucida_Sans_Unicode16h_colcolLit_005B} }, /* code 005B */
   {   7,  14, {abc_fontLucida_Sans_Unicode16h_colcolLit_005C} }, /* code 005C */
   {   4,   8, {abc_fontLucida_Sans_Unicode16h_colcolLit_005D} }, /* code 005D */
   {   8,  16, {abc_fontLucida_Sans_Unicode16h_colcolLit_005E} }, /* code 005E */
   {   7,  14, {abc_fontLucida_Sans_Unicode16h_colcolLit_005F} }, /* code 005F */
   {   8,  16, {abc_fontLucida_Sans_Unicode16h_colcolLit_0060} }, /* code 0060 */
   {   7,  14, {abc_fontLucida_Sans_Unicode16h_colcolLit_0061} }, /* code 0061 */
   {   8,  16, {abc_fontLucida_Sans_Unicode16h_colcolLit_0062} }, /* code 0062 */
   {   7,  14, {abc_fontLucida_Sans_Unicode16h_colcolLit_0063} }, /* code 0063 */
   {   8,  16, {abc_fontLucida_Sans_Unicode16h_colcolLit_0064} }, /* code 0064 */
   {   7,  14, {abc_fontLucida_Sans_Unicode16h_colcolLit_0065} }, /* code 0065 */
   {   5,  10, {abc_fontLucida_Sans_Unicode16h_colcolLit_0066} }, /* code 0066 */
   {   8,  16, {abc_fontLucida_Sans_Unicode16h_colcolLit_0067} }, /* code 0067 */
   {   8,  16, {abc_fontLucida_Sans_Unicode16h_colcolLit_0068} }, /* code 0068 */
   {   4,   8, {abc_fontLucida_Sans_Unicode16h_colcolLit_0069} }, /* code 0069 */
   {   4,   8, {abc_fontLucida_Sans_Unicode16h_colcolLit_006A} }, /* code 006A */
   {   8,  16, {abc_fontLucida_Sans_Unicode16h_colcolLit_006B} }, /* code 006B */
   {   4,   8, {abc_fontLucida_Sans_Unicode16h_colcolLit_006C} }, /* code 006C */
   {  12,  24, {abc_fontLucida_Sans_Unicode16h_colcolLit_006D} }, /* code 006D */
   {   8,  16, {abc_fontLucida_Sans_Unicode16h_colcolLit_006E} }, /* code 006E */
   {   8,  16, {abc_fontLucida_Sans_Unicode16h_colcolLit_006F} }, /* code 006F */
   {   8,  16, {abc_fontLucida_Sans_Unicode16h_colcolLit_0070} }, /* code 0070 */
   {   8,  16, {abc_fontLucida_Sans_Unicode16h_colcolLit_0071} }, /* code 0071 */
   {   5,  10, {abc_fontLucida_Sans_Unicode16h_colcolLit_0072} }, /* code 0072 */
   {   7,  14, {abc_fontLucida_Sans_Unicode16h_colcolLit_0073} }, /* code 0073 */
   {   5,  10, {abc_fontLucida_Sans_Unicode16h_colcolLit_0074} }, /* code 0074 */
   {   8,  16, {abc_fontLucida_Sans_Unicode16h_colcolLit_0075} }, /* code 0075 */
   {   7,  14, {abc_fontLucida_Sans_Unicode16h_colcolLit_0076} }, /* code 0076 */
   {  10,  20, {abc_fontLucida_Sans_Unicode16h_colcolLit_0077} }, /* code 0077 */
   {   8,  16, {abc_fontLucida_Sans_Unicode16h_colcolLit_0078} }, /* code 0078 */
   {   7,  14, {abc_fontLucida_Sans_Unicode16h_colcolLit_0079} }, /* code 0079 */
   {   7,  14, {abc_fontLucida_Sans_Unicode16h_colcolLit_007A} }, /* code 007A */
   {   4,   8, {abc_fontLucida_Sans_Unicode16h_colcolLit_007B} }, /* code 007B */
   {   5,  10, {abc_fontLucida_Sans_Unicode16h_colcolLit_007C} }, /* code 007C */
   {   4,   8, {abc_fontLucida_Sans_Unicode16h_colcolLit_007D} }, /* code 007D */
   {   8,  16, {abc_fontLucida_Sans_Unicode16h_colcolLit_007E} }, /* code 007E */
   {  13,  26, {abc_fontLucida_Sans_Unicode16h_colcolLit_3053} }, /* code 3053 */
   {  14,  28, {abc_fontLucida_Sans_Unicode16h_colcolLit_3061} }, /* code 3061 */
   {  14,  28, {abc_fontLucida_Sans_Unicode16h_colcolLit_306B} }, /* code 306B */
   {  15,  30, {abc_fontLucida_Sans_Unicode16h_colcolLit_306F} }, /* code 306F */
   {  15,  30, {abc_fontLucida_Sans_Unicode16h_colcolLit_3093} }, /* code 3093 */
   {  13,  26, {abc_fontLucida_Sans_Unicode16h_colcolLit_30AB} }, /* code 30AB */
   {  11,  22, {abc_fontLucida_Sans_Unicode16h_colcolLit_30C3} }, /* code 30C3 */
   {  13,  26, {abc_fontLucida_Sans_Unicode16h_colcolLit_30C9} }, /* code 30C9 */
   {  14,  28, {abc_fontLucida_Sans_Unicode16h_colcolLit_30D7} }, /* code 30D7 */
   {  15,  30, {abc_fontLucida_Sans_Unicode16h_colcolLit_30EB} }, /* code 30EB */
   {  14,  28, {abc_fontLucida_Sans_Unicode16h_colcolLit_30EF} }, /* code 30EF */
   {  15,  30, {abc_fontLucida_Sans_Unicode16h_colcolLit_30FC} }, /* code 30FC */
   {  18,  36, {abc_fontLucida_Sans_Unicode16h_colcolLit_4E16} }, /* code 4E16 */
   {  18,  36, {abc_fontLucida_Sans_Unicode16h_colcolLit_4F60} }, /* code 4F60 */
   {  18,  36, {abc_fontLucida_Sans_Unicode16h_colcolLit_597D} }, /* code 597D */
   {  18,  36, {abc_fontLucida_Sans_Unicode16h_colcolLit_676F} }, /* code 676F */
   {  18,  36, {abc_fontLucida_Sans_Unicode16h_colcolLit_754C} }, /* code 754C */
   {  18,  36, {abc_fontLucida_Sans_Unicode16h_colcolLit_B155} }, /* code B155 */
   {  18,  36, {abc_fontLucida_Sans_Unicode16h_colcolLit_B4DC} }, /* code B4DC */
   {  18,  36, {abc_fontLucida_Sans_Unicode16h_colcolLit_C138} }, /* code C138 */
   {  18,  36, {abc_fontLucida_Sans_Unicode16h_colcolLit_C548} }, /* code C548 */
   {  18,  36, {abc_fontLucida_Sans_Unicode16h_colcolLit_C694} }, /* code C694 */
   {  18,  36, {abc_fontLucida_Sans_Unicode16h_colcolLit_C6D4} }, /* code C6D4 */
   {  18,  36, {abc_fontLucida_Sans_Unicode16h_colcolLit_CEF5} }, /* code CEF5 */
   {  18,  36, {abc_fontLucida_Sans_Unicode16h_colcolLit_D558} }, /* code D558 */
   {  12,  24, {abc_fontLucida_Sans_Unicode16h_colcolLit_FF0C} }, /* code FF0C */
   {   8,  16, {abc_fontLucida_Sans_Unicode16h_colcolLit_FF64} }  /* code FF64 */
};

const BFC_FONT_PROP fontLucida_Sans_Unicode16h_colcolLit_Prop28 = {
   0xFF64, /* first character */
   0xFF64, /* last character  */
   &fontLucida_Sans_Unicode16h_colcolLit_CharInfo[ 121],  /* address of first character */
   (const BFC_FONT_PROP *)0				/* pointer to next BFC_FONT_PROP */
};

const BFC_FONT_PROP fontLucida_Sans_Unicode16h_colcolLit_Prop27 = {
   0xFF0C, /* first character */
   0xFF0C, /* last character  */
   &fontLucida_Sans_Unicode16h_colcolLit_CharInfo[ 120],  /* address of first character */
   &fontLucida_Sans_Unicode16h_colcolLit_Prop28			/* pointer to next BFC_FONT_PROP */
};

const BFC_FONT_PROP fontLucida_Sans_Unicode16h_colcolLit_Prop26 = {
   0xD558, /* first character */
   0xD558, /* last character  */
   &fontLucida_Sans_Unicode16h_colcolLit_CharInfo[ 119],  /* address of first character */
   &fontLucida_Sans_Unicode16h_colcolLit_Prop27			/* pointer to next BFC_FONT_PROP */
};

const BFC_FONT_PROP fontLucida_Sans_Unicode16h_colcolLit_Prop25 = {
   0xCEF5, /* first character */
   0xCEF5, /* last character  */
   &fontLucida_Sans_Unicode16h_colcolLit_CharInfo[ 118],  /* address of first character */
   &fontLucida_Sans_Unicode16h_colcolLit_Prop26			/* pointer to next BFC_FONT_PROP */
};

const BFC_FONT_PROP fontLucida_Sans_Unicode16h_colcolLit_Prop24 = {
   0xC6D4, /* first character */
   0xC6D4, /* last character  */
   &fontLucida_Sans_Unicode16h_colcolLit_CharInfo[ 117],  /* address of first character */
   &fontLucida_Sans_Unicode16h_colcolLit_Prop25			/* pointer to next BFC_FONT_PROP */
};

const BFC_FONT_PROP fontLucida_Sans_Unicode16h_colcolLit_Prop23 = {
   0xC694, /* first character */
   0xC694, /* last character  */
   &fontLucida_Sans_Unicode16h_colcolLit_CharInfo[ 116],  /* address of first character */
   &fontLucida_Sans_Unicode16h_colcolLit_Prop24			/* pointer to next BFC_FONT_PROP */
};

const BFC_FONT_PROP fontLucida_Sans_Unicode16h_colcolLit_Prop22 = {
   0xC548, /* first character */
   0xC548, /* last character  */
   &fontLucida_Sans_Unicode16h_colcolLit_CharInfo[ 115],  /* address of first character */
   &fontLucida_Sans_Unicode16h_colcolLit_Prop23			/* pointer to next BFC_FONT_PROP */
};

const BFC_FONT_PROP fontLucida_Sans_Unicode16h_colcolLit_Prop21 = {
   0xC138, /* first character */
   0xC138, /* last character  */
   &fontLucida_Sans_Unicode16h_colcolLit_CharInfo[ 114],  /* address of first character */
   &fontLucida_Sans_Unicode16h_colcolLit_Prop22			/* pointer to next BFC_FONT_PROP */
};

const BFC_FONT_PROP fontLucida_Sans_Unicode16h_colcolLit_Prop20 = {
   0xB4DC, /* first character */
   0xB4DC, /* last character  */
   &fontLucida_Sans_Unicode16h_colcolLit_CharInfo[ 113],  /* address of first character */
   &fontLucida_Sans_Unicode16h_colcolLit_Prop21			/* pointer to next BFC_FONT_PROP */
};

const BFC_FONT_PROP fontLucida_Sans_Unicode16h_colcolLit_Prop19 = {
   0xB155, /* first character */
   0xB155, /* last character  */
   &fontLucida_Sans_Unicode16h_colcolLit_CharInfo[ 112],  /* address of first character */
   &fontLucida_Sans_Unicode16h_colcolLit_Prop20			/* pointer to next BFC_FONT_PROP */
};

const BFC_FONT_PROP fontLucida_Sans_Unicode16h_colcolLit_Prop18 = {
   0x754C, /* first character */
   0x754C, /* last character  */
   &fontLucida_Sans_Unicode16h_colcolLit_CharInfo[ 111],  /* address of first character */
   &fontLucida_Sans_Unicode16h_colcolLit_Prop19			/* pointer to next BFC_FONT_PROP */
};

const BFC_FONT_PROP fontLucida_Sans_Unicode16h_colcolLit_Prop17 = {
   0x676F, /* first character */
   0x676F, /* last character  */
   &fontLucida_Sans_Unicode16h_colcolLit_CharInfo[ 110],  /* address of first character */
   &fontLucida_Sans_Unicode16h_colcolLit_Prop18			/* pointer to next BFC_FONT_PROP */
};

const BFC_FONT_PROP fontLucida_Sans_Unicode16h_colcolLit_Prop16 = {
   0x597D, /* first character */
   0x597D, /* last character  */
   &fontLucida_Sans_Unicode16h_colcolLit_CharInfo[ 109],  /* address of first character */
   &fontLucida_Sans_Unicode16h_colcolLit_Prop17			/* pointer to next BFC_FONT_PROP */
};

const BFC_FONT_PROP fontLucida_Sans_Unicode16h_colcolLit_Prop15 = {
   0x4F60, /* first character */
   0x4F60, /* last character  */
   &fontLucida_Sans_Unicode16h_colcolLit_CharInfo[ 108],  /* address of first character */
   &fontLucida_Sans_Unicode16h_colcolLit_Prop16			/* pointer to next BFC_FONT_PROP */
};

const BFC_FONT_PROP fontLucida_Sans_Unicode16h_colcolLit_Prop14 = {
   0x4E16, /* first character */
   0x4E16, /* last character  */
   &fontLucida_Sans_Unicode16h_colcolLit_CharInfo[ 107],  /* address of first character */
   &fontLucida_Sans_Unicode16h_colcolLit_Prop15			/* pointer to next BFC_FONT_PROP */
};

const BFC_FONT_PROP fontLucida_Sans_Unicode16h_colcolLit_Prop13 = {
   0x30FC, /* first character */
   0x30FC, /* last character  */
   &fontLucida_Sans_Unicode16h_colcolLit_CharInfo[ 106],  /* address of first character */
   &fontLucida_Sans_Unicode16h_colcolLit_Prop14			/* pointer to next BFC_FONT_PROP */
};

const BFC_FONT_PROP fontLucida_Sans_Unicode16h_colcolLit_Prop12 = {
   0x30EF, /* first character */
   0x30EF, /* last character  */
   &fontLucida_Sans_Unicode16h_colcolLit_CharInfo[ 105],  /* address of first character */
   &fontLucida_Sans_Unicode16h_colcolLit_Prop13			/* pointer to next BFC_FONT_PROP */
};

const BFC_FONT_PROP fontLucida_Sans_Unicode16h_colcolLit_Prop11 = {
   0x30EB, /* first character */
   0x30EB, /* last character  */
   &fontLucida_Sans_Unicode16h_colcolLit_CharInfo[ 104],  /* address of first character */
   &fontLucida_Sans_Unicode16h_colcolLit_Prop12			/* pointer to next BFC_FONT_PROP */
};

const BFC_FONT_PROP fontLucida_Sans_Unicode16h_colcolLit_Prop10 = {
   0x30D7, /* first character */
   0x30D7, /* last character  */
   &fontLucida_Sans_Unicode16h_colcolLit_CharInfo[ 103],  /* address of first character */
   &fontLucida_Sans_Unicode16h_colcolLit_Prop11			/* pointer to next BFC_FONT_PROP */
};

const BFC_FONT_PROP fontLucida_Sans_Unicode16h_colcolLit_Prop9 = {
   0x30C9, /* first character */
   0x30C9, /* last character  */
   &fontLucida_Sans_Unicode16h_colcolLit_CharInfo[ 102],  /* address of first character */
   &fontLucida_Sans_Unicode16h_colcolLit_Prop10			/* pointer to next BFC_FONT_PROP */
};

const BFC_FONT_PROP fontLucida_Sans_Unicode16h_colcolLit_Prop8 = {
   0x30C3, /* first character */
   0x30C3, /* last character  */
   &fontLucida_Sans_Unicode16h_colcolLit_CharInfo[ 101],  /* address of first character */
   &fontLucida_Sans_Unicode16h_colcolLit_Prop9			/* pointer to next BFC_FONT_PROP */
};

const BFC_FONT_PROP fontLucida_Sans_Unicode16h_colcolLit_Prop7 = {
   0x30AB, /* first character */
   0x30AB, /* last character  */
   &fontLucida_Sans_Unicode16h_colcolLit_CharInfo[ 100],  /* address of first character */
   &fontLucida_Sans_Unicode16h_colcolLit_Prop8			/* pointer to next BFC_FONT_PROP */
};

const BFC_FONT_PROP fontLucida_Sans_Unicode16h_colcolLit_Prop6 = {
   0x3093, /* first character */
   0x3093, /* last character  */
   &fontLucida_Sans_Unicode16h_colcolLit_CharInfo[  99],  /* address of first character */
   &fontLucida_Sans_Unicode16h_colcolLit_Prop7			/* pointer to next BFC_FONT_PROP */
};

const BFC_FONT_PROP fontLucida_Sans_Unicode16h_colcolLit_Prop5 = {
   0x306F, /* first character */
   0x306F, /* last character  */
   &fontLucida_Sans_Unicode16h_colcolLit_CharInfo[  98],  /* address of first character */
   &fontLucida_Sans_Unicode16h_colcolLit_Prop6			/* pointer to next BFC_FONT_PROP */
};

const BFC_FONT_PROP fontLucida_Sans_Unicode16h_colcolLit_Prop4 = {
   0x306B, /* first character */
   0x306B, /* last character  */
   &fontLucida_Sans_Unicode16h_colcolLit_CharInfo[  97],  /* address of first character */
   &fontLucida_Sans_Unicode16h_colcolLit_Prop5			/* pointer to next BFC_FONT_PROP */
};

const BFC_FONT_PROP fontLucida_Sans_Unicode16h_colcolLit_Prop3 = {
   0x3061, /* first character */
   0x3061, /* last character  */
   &fontLucida_Sans_Unicode16h_colcolLit_CharInfo[  96],  /* address of first character */
   &fontLucida_Sans_Unicode16h_colcolLit_Prop4			/* pointer to next BFC_FONT_PROP */
};

const BFC_FONT_PROP fontLucida_Sans_Unicode16h_colcolLit_Prop2 = {
   0x3053, /* first character */
   0x3053, /* last character  */
   &fontLucida_Sans_Unicode16h_colcolLit_CharInfo[  95],  /* address of first character */
   &fontLucida_Sans_Unicode16h_colcolLit_Prop3			/* pointer to next BFC_FONT_PROP */
};

const BFC_FONT_PROP fontLucida_Sans_Unicode16h_colcolLit_Prop1 = {
   0x0020, /* first character */
   0x007E, /* last character  */
   &fontLucida_Sans_Unicode16h_colcolLit_CharInfo[   0],  /* address of first character */
   &fontLucida_Sans_Unicode16h_colcolLit_Prop2			/* pointer to next BFC_FONT_PROP */
};

const BFC_FONT fontLucida_Sans_Unicode16h_colcolLit = {
   0x01020702,  /* font type = FONTTYPE_PROP | LITTLE_ENDIAN | COLUMN_BASED | COLUMN_PREFERRED | ENCODING_UNICODE | DATALENGTH_8 */
   16,  /* font height in pixels   */
   13,  /* font ascent (baseline) in pixels  */
   0 ,  /* reversed, =0 */
   {&fontLucida_Sans_Unicode16h_colcolLit_Prop1}  
};
